### ISSUE TITLE
EMC isnt working anymore

### ISSUE THREAD

**Issue by LikMeToez** [FTBTeam/FTB-Builders-Paradise#70]
* **Modpack Version**: 1.5.0

* **Issue**: EMC just dissapeared and just turned into a negative number i have 50 final bonsai trees and 15 mk15's my 4E turned to -4E and the EMC counter became invisible like the modpack is gone

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: I don't know

* **Mod/s Affected**: emcbuilderswand-1.12.2-1.8.jar

* **Known Fix**: I don't know

**Comment by freund17** [comment]
This has been discussed in
https://github.com/sinkillerj/ProjectE/issues/1887 and
https://github.com/LatvianModder/Project-EX/issues/50.

And seems to have been fixed in https://www.curseforge.com/minecraft/mc-mods/project-ex/files/2739323.
One minor Version after the one used in Builders Paradise 1.5.0.

**Comment by Sunekaer** [comment]
1.6.0 is out
